amrnb
amrwb
recode
perl-Cstools
perl-Unicode-Map
perl-Unicode-Map8
enca
libass
libcdaudio
celt
libdc1394
libdca
libmp4v2
faac
faad2
flite
ladspa_sdk
fluidsynth | LADSPA=yes
gsm
libkate
liblrdf
libmodplug
libmimic
libmusicbrainz
libofa
libdv
schroedinger
gts
graphviz
apache-ant
openjdk
libaacs
libbdplus
libbluray | BDJAVA=yes
decklink-sdk
libfdk-aac
hdf5
libxkbcommon
qt5
qt5-webkit
OpenBLAS
numpy
python3
numpy3
opencv | CVFFMPEG=no CVDOCS=yes
gavl
frei0r
libgme
libiec61883
libavc1394
libilbc
libmodplug
OpenAL
opencore-amr
opus
lua
libquvi-scripts
libquvi
rtmpdump
snappy
speex
lame
twolame
vid.stab
libwebp
x264
x265
xvidcore
zeromq
zvbi
jack-audio-connection-kit
ffmpeg | ASS=yes BLURAY=yes CELT=yes DC1394=yes DECKLINK=yes FAAC=yes FDK_AAC=yes FLITE=yes FREI0R=yes GME=yes GSM=yes IEC61883=yes ILBC=yes LADSPA=yes LAME=yes MODPLUG=yes OPENAL=yes OPENCORE=yes OPENCV=yes OPENSSL=yes OPUS=yes QUVI=yes RTMP=yes SCHROEDINGER=yes SNAPPY=yes SPEEX=yes TWOLAME=yes VIDSTAB=yes X264=yes X265=yes XVID=yes ZMQ=yes ZVBI=yes
libquicktime
lv2
libcuefile
libreplaygain
musepack-tools
soundtouch
swfdec
xawplus
TiMidity++ | JACK=yes SPEEX=yes XAW3D=yes 
